{{- if .Values.image.credentials.create -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-registry-secret
  labels:
    {{- include "trawler.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end -}}
