{{ if .Values.extraSecretVars }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "trawler.fullname" . }}-secrets-extra
  labels:
    {{- include "trawler.labels" . | nindent 4 }}
type: Opaque
data:
{{ toYaml .Values.extraSecretVars | indent 2 }}
{{ end }}
