{{- if .Values.ingress.istio.enabled -}}
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ include "dash.fullname" . }}
  labels:
    {{- include "dash.labels" . | nindent 4 }}
spec:
  host: {{ include "dash.fullname" . }}
  trafficPolicy:
    loadBalancer:
      simple: {{ .Values.ingress.istio.loadBalancerType }}
{{- if and .Values.ingress.istio.enabled (eq .Values.ingress.istio.mtlsMode "STRICT") }}
    tls:
      mode: ISTIO_MUTUAL
{{- end }}
{{- end }}
