{{- if .Values.ingress.k8sIngress.enabled -}}
---
{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" -}}
apiVersion: networking.k8s.io/v1
{{- else if .Capabilities.APIVersions.Has "networking.k8s.io/v1beta1/Ingress" -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ template "dash.fullname" . }}
  labels:
    {{- include "dash.labels" . | nindent 4 }}
  {{- with .Values.ingress.k8sIngress.annotations }}
  annotations:
    {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.k8sIngress.tls }}
  tls:
    {{- range .Values.ingress.k8sIngress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
  {{- if .Values.ingress.hosts }}
    {{- range .Values.ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
        - path: {{ $.Values.ingress.path }}
        {{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
          pathType: Prefix
          backend:
            service:
              name: {{ template "dash.fullname" $ }}
              port:
                number: {{ $.Values.service.port }}
        {{- else }}
          backend:
            serviceName: {{ template "dash.fullname" $ }}
            servicePort: {{ $.Values.service.port }}
        {{- end }}
    {{- end }}
  {{- end }}
{{- end -}}
