---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Chart.Name }}-first-scrape
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "2"
    # "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      serviceAccount: {{ .Chart.Name }}-first-scrape-sa
      containers:
      - name: {{ .Chart.Name }}-first-scrape
        image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        command: ["npm"]
        args:
          - "run"
          - "cli:cronjob:trigger"
        env:
          - name: CRONJOB_NAME
            value: {{ .Chart.Name }}-scheduled-scrape
          - name: CRONJOB_NAMESPACE
            value: {{ .Release.Namespace }}
          - name: CLI_PATH
            value: ./cli.js
        envFrom:
          - secretRef:
              name: {{ include "dash.fullname" . }}-secrets
{{- if or .Values.extraConfigVars .Values.extraSecretVars }}
{{- if .Values.extraConfigVars }}
          - configMapRef:
              name: {{ include "dash.fullname" . }}-config-extra
{{- end }}
{{ if .Values.extraSecretVars }}
          - secretRef:
              name: {{ include "dash.fullname" . }}-secrets-extra
{{- end }}
{{- end }}
      restartPolicy: Never
  backoffLimit: 0
