---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Chart.Name }}-first-scrape-sa
  labels:
    {{- include "dash.labels" . | nindent 4 }}
{{- if .Values.image.credentials.create }}
imagePullSecrets:
- name: {{ .Chart.Name }}-registry-secret
{{- else if ne .Values.image.credentials.secretRef "" }}
imagePullSecrets:
- name: {{ .Values.image.credentials.secretRef }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Chart.Name }}-first-scrape
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get","watch","list"]
  - apiGroups: ["batch"]
    resources: ["*"]
    verbs: ["create","get","watch","list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Chart.Name }}-first-scrape
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Chart.Name }}-first-scrape
subjects:
- kind: ServiceAccount
  name: {{ .Chart.Name }}-first-scrape-sa
  namespace: {{ .Release.Namespace }}
