---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dash.fullname" . }}-secrets
  labels:
    {{- include "dash.labels" . | nindent 4 }}
type: Opaque
data:
  SECURITY_JWT_SECRET: "{{ .Values.global.jwtSecret | b64enc }}"
  DATABASE_CONNECTION_HOST: "{{ .Values.global.postgres.host | default "minesweeper-postgresql" | b64enc }}"
  DATABASE_CONNECTION_PORT: "{{ .Values.global.postgres.port | default "5432" | toString | b64enc }}"
  DATABASE_CONNECTION_DATABASE: "{{ .Values.global.postgres.database | default "postgres" | b64enc }}"
  DATABASE_CONNECTION_USERNAME: "{{ .Values.global.postgres.username | default "postgres" | b64enc }}"
  DATABASE_CONNECTION_PASSWORD: "{{ .Values.global.postgres.password | default "postgres" | b64enc }}"
  RABBITMQ_HOST_NAME: "{{ .Values.global.rabbitmq.host | default "minesweeper-rabbitmq" | b64enc }}"
  RABBITMQ_PORT: "{{ .Values.global.rabbitmq.port | default "5672" | toString | b64enc }}"
  RABBITMQ_USERNAME: "{{ .Values.global.rabbitmq.username | default "guest" | b64enc }}"
  RABBITMQ_PASSWORD: "{{ .Values.global.rabbitmq.password | default "guest" | b64enc }}"
  MSG_QUEUE_NAME_IMAGE_SCANNER: "{{ .Values.global.rabbitmq.queueName | default "trawler_queue" | b64enc }}"
{{- if ne .Values.email.method "" }}
  EMAIL_CONFIG_USE: "{{ .Values.email.method  | b64enc }}"
{{- if eq .Values.email.method "SENDGRID" }}
  EMAIL_SENDGRID_API_KEY: "{{ .Values.email.sendgridApiKey  | b64enc }}"
{{- else if eq .Values.email.method "SMTP" }}
  EMAIL_SMTP_HOST: "{{ .Values.email.smtp.host | b64enc}}"
  EMAIL_SMTP_PORT: "{{ .Values.email.smtp.port | toString | b64enc }}"
  EMAIL_SMTP_SECURE_CONNECTION: "{{ .Values.email.smtp.tlsRequired | ternary 1 0 | toString | b64enc }}"
  EMAIL_SMTP_AUTH_USER: "{{ .Values.email.smtp.user | b64enc }}"
  EMAIL_SMTP_AUTH_PASSWORD: "{{ .Values.email.smtp.password | b64enc }}"
{{- end }}
  EMAIL_DEFAULT_SENDER_EMAIL: "{{ .Values.email.senderEmail | b64enc }}"
  EMAIL_SYSTEM_ERROR_REPORT_ENABLE: "{{ .Values.email.enableSystemErrorEmail | ternary 1 0 | toString | b64enc }}"
  EMAIL_SYSTEM_ERROR_REPORT: "{{ .Values.email.systemErrorMailTo | b64enc }}"
{{- end }}
