{{- if .Values.ingress.istio.enabled -}}
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "dash.fullname" . }}
  labels:
    {{- include "dash.labels" . | nindent 4 }}
spec:
{{- with .Values.ingress.istio.gateways }}
  gateways:
{{ toYaml . | indent 4 }}
{{- end }}
{{- with .Values.ingress.hosts }}
  hosts:
{{ toYaml . | indent 4 }}
{{- end }}
  http:
  - match:
    - uri:
       prefix: .Values.ingress.path
    route:
    - destination:
        host: {{ include "dash.fullname" . }}
        port:
          number: {{ .Values.service.port }}
{{- end }}
