{{ if .Values.secretData }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rabbitmq.fullname" . }}
  labels:
    {{- include "rabbitmq.labels" . | nindent 4 }}
type: Opaque
data:
{{ toYaml .Values.secretData | indent 2 }}
{{ end }}
